version: '3'

services:
  # Runs the Python server process:
  # Runs the JS client build and serve process:
  web:
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
    depends_on:
      - postgres
      - redis
    links:
      - "postgres:db"
      - redis
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:8080:8080"

  # Runs the database process:
  postgres:
    image: postgres:10.6
    environment:
      - POSTGRES_USER=metashare

  # Runs the queue process:
  redis:
    image: redis:5.0

  # Sets up git hooks for local development:
  githooks:
    build:
      context: .
      dockerfile: ./compose/githooks/Dockerfile
    volumes:
      - ./.git:/tmp/.git
      - ./hooks:/tmp/hooks
