version: '3'

services:
  # Runs the database process:
  postgres:
    image: postgres:10.6
    environment:
      - POSTGRES_USER=metashare

  # Runs the Python server process:
  web:
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
    depends_on:
      - postgres
    links:
      - "postgres:db"
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"

  # Runs the JS client build and serve process:
  client:
    build:
      context: .
      dockerfile: ./compose/client/Dockerfile
    depends_on:
      - web
    links:
      - "web:backend"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:8080:8080"

  # Sets up git hooks for local development:
  githooks:
    build:
      context: .
      dockerfile: ./compose/githooks/Dockerfile
    volumes:
      - ./.git:/tmp/.git
      - ./hooks:/tmp/hooks
