version: 2.1
jobs:
  build:
    working_directory: ~/metashare
    docker:
      - image: wlonk/oddbird
    steps:
      - checkout
      - restore_cache:
          keys:
            - metashare-py-{{ checksum "Pipfile.lock" }}
      - restore_cache:
          keys:
            - metashare-npm-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
            python3 -m venv venv
            . venv/bin/activate
            pipenv install --dev --deploy --ignore-pipfile
      - run:
          name: Compile Front-End Assets
          command: yarn prod
      - persist_to_workspace:
          root: .
          paths:
            - ./venv
            - ./node_modules
      - save_cache:
          key: metashare-py-{{ checksum "Pipfile.lock" }}
          paths:
            - ./venv
      - save_cache:
          key: metashare-npm-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  lint:
    working_directory: ~/metashare
    docker:
      - image: wlonk/oddbird
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            yarn lint

  test-client:
    working_directory: ~/metashare
    docker:
      - image: wlonk/oddbird
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test JS
          command: yarn test:js:coverage
      - store_artifacts:
          path: coverage
          destination: js-reports
      - store_test_results:
          path: coverage
      - persist_to_workspace:
          root: .
          paths:
            - coverage

  test-python:
    working_directory: ~/metashare
    docker:
      - image: wlonk/oddbird
        environment:
          BUCKETEER_AWS_ACCESS_KEY_ID: circle_test
          BUCKETEER_AWS_SECRET_ACCESS_KEY: circle_test
          BUCKETEER_BUCKET_NAME: circle_test
          DATABASE_URL: postgres://ubuntu@localhost:5432/circle_test
          DB_ENCRYPTION_KEY: MMkDMBfYL0Xoz3Xu1ENs3AkdCZdJoks5PNlUBkK7KDc=
          DJANGO_DEBUG: False
          DJANGO_HASHID_SALT: test_hash_id
          DJANGO_SECRET_KEY: test_secret_key
          DJANGO_SETTINGS_MODULE: config.settings.test
          SECURE_SSL_REDIRECT: False
      - image: circleci/redis:latest
      - image: circleci/postgres:latest
        environment:
          AWS_ACCESS_KEY_ID: None
          AWS_BUCKET_NAME: None
          AWS_SECRET_ACCESS_KEY: None
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: circle_test
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Database Migrations
          command: |
            . venv/bin/activate
            python manage.py migrate --no-input
      - run:
          name: Test Python
          command: |
            . venv/bin/activate
            pytest --junitxml=pycov/pytest-junit.xml
      - store_artifacts:
          path: htmlcov
          destination: py-reports
      - store_test_results:
          path: pycov
      - persist_to_workspace:
          root: .
          paths:
            - .coverage

  report-test-coverage:
    working_directory: ~/metashare
    docker:
      - image: wlonk/oddbird
    environment:
      COVERALLS_PARALLEL: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Report Test Coverage
          command: |
            . venv/bin/activate
            yarn test:js:report-coverage
            yarn test:py:report-coverage
            curl -k "https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}" -d "payload[build_num]=${CIRCLE_BUILD_NUM}&payload[status]=done"
      - run:
          name: Check Test Coverage
          command: |
            . venv/bin/activate
            yarn test:js:check-coverage
            yarn test:py:check-coverage

  build-docs:
    working_directory: ~/metashare
    docker:
      - image: wlonk/oddbird
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Documentation
          command: |
            . venv/bin/activate
            cd docs
            make html

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test-client:
          requires:
            - build
      - test-python:
          requires:
            - build
      - build-docs:
          requires:
            - build
      - report-test-coverage:
          requires:
            - test-client
            - test-python
