version: '3'

services:
  web:
    volumes:
      - vscode-server:/root/.vscode-server
      - /var/run/docker.sock:/var/run/docker.sock
    # Override command to prevent container crashing if webpack build exits
    command: sleep infinity

volumes:
  vscode-server: {}
